version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "18876:80"
        depends_on:
            - app
        container_name: peach_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: peach_app

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lardocker
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "18101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: peach_db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: peach_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "18081:80"

    npm:
        image: node:16
        container_name: peach_npm
        user: "1000:1000"
        volumes:
            - ./src:/var/www
        working_dir: /var/www
